name: Release to Google Play Store

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: read

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4 -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dkotlin.incremental=false

jobs:
  release:
    name: Build & Release to Play Store
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Run tests before release
        run: |
          ./gradlew lintRelease testReleaseUnitTest --parallel --build-cache
          
      - name: Build release AAB (Android App Bundle)
        run: |
          ./gradlew bundleRelease --parallel --build-cache
          
      - name: Upload AAB to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.bizzarosn.heightmark
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal  # Options: internal, alpha, beta, production
          status: completed
          inAppUpdatePriority: 2
          whatsNewDirectory: metadata/whatsnew
          
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/reports/lint-results-release.html
          retention-days: 30
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: HeightMark ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed
            
            Release notes for HeightMark version ${{ github.ref_name }}
            
            ### Features
            - Real-time elevation tracking
            - GPS-based altitude measurement
            - Metric/Imperial unit switching
            - Material Design UI with dark mode support
            
            ### Technical Details
            - Built with Android SDK 35
            - Optimized for accuracy with averaged readings
            - Robust location permission handling
            
            **Available on Google Play Store**
